- platform: mqtt
  name: livingroom_hvac
  qos: 1
  initial: 20
  availability_topic: "sensor/room/available"
  payload_available: "true"
  payload_not_available: "false"
  current_temperature_topic: "sensor/room/temperature"
  temperature_state_topic: "sensor/room/temperature"
  temperature_command_topic: "void/hvac/temperature/set"
  mode_state_topic: "void/hvac/mode/state"
  mode_command_topic: "void/hvac/mode/set"
- platform: mqtt
  name: bedroom_hvac
  qos: 1
  initial: 20
  availability_topic: "sensor/bedroom/available"
  payload_available: "true"
  payload_not_available: "false"
  current_temperature_topic: "sensor/bedroom/temperature"
  temperature_state_topic: "sensor/bedroom/temperature"
  temperature_command_topic: "void/hvac/temperature/set"
  mode_state_topic: "void/hvac/mode/state"
  mode_command_topic: "void/hvac/mode/set"
- platform: smartir
  name: Conditioner
  unique_id: conditioner
  device_code: 2000
  controller_data: remote.xiaomi_miio_192_168_1_239
  temperature_sensor: sensor.0x00158d000227d566_temperature
  humidity_sensor: sensor.0x00158d000227d566_humidity
  power_sensor: input_boolean.conditioner